### ISSUE TITLE
Unsupported Swagger (v2) datatype: "number"

### ISSUE THREAD

**Issue by bdarlt** [Teebytes/TnT-Fuzzer#21]
**Describe the bug**
The v2 [Swagger datatype definitions](https://swagger.io/docs/specification/data-models/data-types/#numbers) include "number" what can be an int, float or double. In the spirit of fuzzing, we can probably just pretend "int with decimals".

**To Reproduce**
1. Use a Swagger JSON file with "number"

**Expected behavior**
I'm not 100% sure what a random "number" should be. But Python uses "uniform" from the random class to do it.

**Comment by xenobyte** [comment]
Solved with #22
