### ISSUE TITLE
Add option to write log to file and read file as input to reproduce all actions

### ISSUE THREAD

**Issue by Thoiz** [Teebytes/TnT-Fuzzer#3]
Add option to write log to file. The file can be supplied as input to reproduce all actions that were logged in the file.
This might be helpful in case the information logged produced an incident or crash on the given API. This way the whole procedure can be reproduced.

**Comment by xenobyte** [comment]
You could solve this by redirecting stdout. ```tntfuzzer --url http://example.com:8080/v2/swagger.json --iterations 100 --log_all > fuzz.log```
