### ISSUE TITLE
Patch request make the process crash

### ISSUE THREAD

**Issue by GuilloOme** [Teebytes/TnT-Fuzzer#37]
When the swagger file contains PATCH route, the fuzzer crash with the stacktrace: 
```
...

  File ".../TnT-Fuzzer/tntfuzzer/tntfuzzer.py", line 189, in main
    tnt.start()
  File ".../TnT-Fuzzer/tntfuzzer/tntfuzzer.py", line 115, in start
    log = validator.evaluate(response, path[op_code]['responses'], self.log_unexpected_errors_only)
  File ".../TnT-Fuzzer/tntfuzzer/core/resultvalidatior.py", line 10, in evaluate
    result_log['status_code'] = response.status_code
AttributeError: 'NoneType' object has no attribute 'status_code'
```

**To Reproduce**
1. run the fuzzer on a swagger with PATCH route

**Expected behavior**
Calling the PATCH route like the other routes

**Used Software (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python 3.7
 - Application-Version commit #662e3d77a4aabd13bf675e807a391ef1af99105f

**Comment by Thoiz** [comment]
Thanks for your feedback @GuilloOme! The fuzzer was missing the patch operation directive. Fixed in PR #38
