### ISSUE TITLE
ImportError: No module named parse

### ISSUE THREAD

**Issue by SpeTr0x** [Teebytes/TnT-Fuzzer#46]
error trace: 

Traceback (most recent call last):
  File "tntfuzzer.py", line 13, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse

`pip install parse`  parse installed without errors, but the traceback error stating parse, is still persisting

**Comment by xenobyte** [comment]
Could you provide some more details?

Which Software are you using?
 - OS: [e.g. Linux or macOS]
 - Python [e.g. python 2.7, python 3]
 - Application-Version [e.g. 1.0.0]

Which steps are necessary to reproduce the behavior?

**Comment by DanielRuf** [comment]
Same here. Ubuntu 18 with the latest commit.

python3 --version
Python 3.6.8


python --version
Python 2.7.15+

**Comment by xenobyte** [comment]
TnT-Fuzzer shifted support away from python 2 to **python 3.7** 

did you install the dependencies with `pip install -r requirements.txt` ?

Which version are you using?

**Comment by DanielRuf** [comment]
`pip` is Python 2, I tried it with `pip3` and `pip` afaik.

**Comment by xenobyte** [comment]
```
pip -V
pip 19.3.1 from /Users/timo/tntfuzzer_env/lib/python3.6/site-packages/pip (python 3.6)
```

Did you try the commands in my last comment? Does it work for you?

**Comment by DanielRuf** [comment]
I tried these command and got errors with pyhon and python3.

Why was this issue closed?

I think this can be reproduced on CI.

**Comment by xenobyte** [comment]
I was not able to reproduce the error on my setup and since there was no reply on my last comment, I thought it might not be an issue anymore. I just updated the CI to build on Ubuntu 18 (bionic) and I am still not able to reproduce the issue. Could you provide a complete console log?

**Comment by abandyop** [comment]
Hi,
I'm getting this error : 
$$ python tntfuzzer/tntfuzzer.py
Traceback (most recent call last):
  File "tntfuzzer/tntfuzzer.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by barrett092** [comment]
same error
